refactor:deploy backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -251,75 +251,75 @@ jobs:
             # exit 1
       # Here's where you will add some code to rollback on failure
 
-  run-migrations: #preparing data needed for backend application to run
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - attach_workspace:
-          at: ~/
-          #paths:
-            #- project/
-      - run:
-          name: awscli install
-          command: |
-            sudo apt-get -y -qq update
-            sudo apt-get -y -qq install python3
-            sudo apt-get -qq install awscli
-            pwd
-            ls -la
-      - run:
-          name: add values to .env files # Create a `backend/.env` file and add those values there dynamically
-          command: |
-            echo PWD
-            pwd
-            #ls -la
-            touch backend/.env
-            echo ENVIRONMENT=production >> "backend/.env"
-            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
-            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
-            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
-            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
-            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-      - run:
-          name: Run migrations
-          command: |
-            cd backend
-            npm install
-            npm run build
-            pwd
-            echo " THIS IS .env CONTENTS:"
-            cat .env
-            echo 'DUMP MIGRATIONS'
-            echo 'hello world!!' > migrations_dump.txt
-            npm run migrations >> migrations_dump.txt
-            echo "generated file!"
-            pwd
-            ls -la
-            echo 'DISPLAY CONTENTS'
-            echo '*****************'
-            cat migrations_dump.txt
-      - run:
-          name: Send migration results to memstash
-          command: |
-            if grep -q "has been executed successfully" migrations.txt; then
-              curl -H "Content-Type: text/plain" -H "token: 41becf56-e770-4630-a0e7-4f17f1d66667" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            else
-              curl -H "Content-Type: text/plain" -H "token: 41becf56-e770-4630-a0e7-4f17f1d66667" --request PUT --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            fi
-            SUCCESS=$(curl -H "token: 41becf56-e770-4630-a0e7-4f17f1d66667" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
-            echo "${SUCCESS}"
-      - save_cache:
-          paths: [backend/node_modules]
-          key: backend-build
-#      - revert-migrations
-#      - destroy-environment
+#  run-migrations: #preparing data needed for backend application to run
+#    docker:
+#      - image: circleci/node:13.8.0
+#    steps:
+#      - checkout
+#      - restore_cache:
+#          keys: [backend-build]
+#      - attach_workspace:
+#          at: ~/
+#          #paths:
+#            #- project/
+#      - run:
+#          name: awscli install
+#          command: |
+#            sudo apt-get -y -qq update
+#            sudo apt-get -y -qq install python3
+#            sudo apt-get -qq install awscli
+#            pwd
+#            ls -la
+#      - run:
+#          name: add values to .env files # Create a `backend/.env` file and add those values there dynamically
+#          command: |
+#            echo PWD
+#            pwd
+#            #ls -la
+#            touch backend/.env
+#            echo ENVIRONMENT=production >> "backend/.env"
+#            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
+#            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
+#            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
+#            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
+#            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
+#            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
+#            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
+#            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
+#            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
+#      - run:
+#          name: Run migrations
+#          command: |
+#            cd backend
+#            npm install
+#            npm run build
+#            pwd
+#            echo " THIS IS .env CONTENTS:"
+#            cat .env
+#            echo 'DUMP MIGRATIONS'
+#            echo 'hello world!!' > migrations_dump.txt
+#            npm run migrations >> migrations_dump.txt
+#            echo "generated file!"
+#            pwd
+#            ls -la
+#            echo 'DISPLAY CONTENTS'
+#            echo '*****************'
+#            cat migrations_dump.txt
+#      - run:
+#          name: Send migration results to memstash
+#          command: |
+#            if grep -q "has been executed successfully" migrations.txt; then
+#              curl -H "Content-Type: text/plain" -H "token: 41becf56-e770-4630-a0e7-4f17f1d66667" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+#            else
+#              curl -H "Content-Type: text/plain" -H "token: 41becf56-e770-4630-a0e7-4f17f1d66667" --request PUT --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+#            fi
+#            SUCCESS=$(curl -H "token: 41becf56-e770-4630-a0e7-4f17f1d66667" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
+#            echo "${SUCCESS}"
+#      - save_cache:
+#          paths: [backend/node_modules]
+#          key: backend-build
+##      - revert-migrations
+##      - destroy-environment
 #
 #  deploy-frontend:
 #    docker:
@@ -342,22 +342,39 @@ jobs:
 #            # your code here
 #      # Here's where you will add some code to rollback on failure
 #
-#  deploy-backend:
-#    docker:
-#      # Docker image here that supports Ansible
-#    steps:
-#      # Checkout code from git
-#      # Add ssh keys with fingerprint
-#      # attach workspace
-#      - run:
-#          name: Install dependencies
-#          command: |
-#            # your code here
-#      - run:
-#          name: Deploy backend
-#          command: |
-#            # your code here
-#      # Here's where you will add some code to rollback on failure
+  deploy-backend:
+    docker:
+      - image: python:3.7-alpine3.11
+      # Docker image here that supports Ansible
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+            - "c3:56:8d:ca:23:f3:14:0b:91:45:3e:a8:55:ac:d6:c7"
+      - attach_workspace:
+          at: ~/
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            apk add --update ansible
+            pip3 install --upgrade pip \
+              && pip3 install awscli
+      - run:
+          name: Deploy backend
+          command: |
+            # your code here
+            pwd
+            ls -al
+            cd ~
+            cat ~/project/.circleci/ansible/inventory.txt
+            export ANSIBLE_HOST_KEY_CHECKING=False
+            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/deploy-backend.yml
+            # exit 1
+      # Here's where you will add some code to rollback on failure
 #
 #  smoke-test:
 #    docker:
@@ -437,10 +454,11 @@ workflows:
               only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-#      - deploy-frontend:
+#      - run-migrations:
+#          requires: [configure-infrastructure]
+#      - deploy-frontend #:
 #          requires: [run-migrations]
+      - deploy-backend
 #      - deploy-backend:
 #          requires: [run-migrations]
 #      - smoke-test:
