smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -376,28 +376,45 @@ jobs:
             # exit 1
       # Here's where you will add some code to rollback on failure
 #
-#  smoke-test:
-#    docker:
-#      # Lightweight Docker image
-#    steps:
-#      # Checkout code from git
-#      - run:
-#          name: Install dependencies
-#          command: |
-#            # your code here
+  smoke-test:
+    docker:
+      - image: python:3.7-alpine3.11
+      # Lightweight Docker image
+    steps:
+      - checkout
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            apk add curl
+            pip3 install --upgrade pip \
+              && pip3 install awscli
+            # your code here
 #      - run:
 #          name: Get backend url
 #          command: |
 #            # your code here
-#      - run:
-#          name: Backend smoke test.
-#          command: |
-#            # your code here
-#      - run:
-#          name: Frontend smoke test.
-#          command: |
-#            # your code here
-#      # Here's where you will add some code to rollback on failure
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            BACKEND_URL="http://$(cat /tmp/backend):3030/api/status"
+            echo "curl-ing ${BACKEND_URL}"
+            if curl ${BACKEND_URL}
+              then exit 0
+              else exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+            echo "curl-ing ${URL}"
+            if curl ${URL} | grep -q "Welcome"
+              then exit 0
+              else exit 1
+            fi
+      # Here's where you will add some code to rollback on failure
 #
 #  cloudfront-update:
 #    docker:
