cloutfront-update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -406,32 +406,42 @@ jobs:
 #            export URL="http://$BACKEND_IP:3030/api/status"
 #            echo $URL
 #            curl $URL
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
-            echo "curl-ing ${URL}"
-            if curl ${URL} | grep -q "Welcome"
-              then exit 0
-              else exit 1
-            fi
+#      - run:
+#          name: Frontend smoke test.
+#          command: |
+#            # your code here
+#            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+#            echo "curl-ing ${URL}"
+#            if curl ${URL} | grep -q "Welcome"
+#              then exit 0
+#              else exit 1
+#            fi
       # Here's where you will add some code to rollback on failure
 #
-#  cloudfront-update:
-#    docker:
-#      # Docker image here that supports AWS CLI
-#    steps:
-#      # Checkout code from git
-#      - run:
+  cloudfront-update:
+    docker:
+      - image: amazon/aws-cli
+      # Docker image here that supports AWS CLI
+    steps:
+      # Checkout code from git
+      - run:
 #          name: Install dependencies
 #          command: |
 #            # your code here
-#      - run:
-#          name: Update cloudfront distribution
-#          command: |
-#            # your code here
-#      # Here's where you will add some code to rollback on failure
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            # your code here
+            # aws cloudformation deploy \
+            #   --template-file .circleci/files/cloudfront.yml \
+            #   --tags project=project4-cloudfront \
+            #   --stack-name udapeople-cloudfront \
+            #   --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID} &
+            aws cloudformation update-stack \
+            --use-previous-template \
+            --stack-name udapeople-cloudfront \
+            --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID},UsePreviousValue=false
+      # Here's where you will add some code to rollback on failure
 
 cleanup:
     docker:
@@ -484,7 +494,7 @@ workflows:
           requires: [deploy-backend]
 #      - smoke-test:
 #          requires: [deploy-backend, deploy-frontend]
-#      - cloudfront-update:
-#          requires: [smoke-test]
+      - cloudfront-update:
+          requires: [smoke-test]
 #      - cleanup:
 #          requires: [cloudfront-update]
