fix:cleanup

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -376,81 +376,81 @@ jobs:
             # exit 1
       # Here's where you will add some code to rollback on failure
 #
-  smoke-test:
-    docker:
-      # Lightweight Docker image
-      - image: python:3.7-alpine3.11
-    steps:
-      # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-            apk add curl
-            pip3 install --upgrade pip \
-              && pip3 install awscli
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-            BACKEND_IP=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/deployment)
-            echo "I think the Backend IP is ${BACKEND_IP}"
-            echo ${BACKEND_IP} > /tmp/backend
-            echo -n "The file /tmp/backend contains IP:"
-            cat /tmp/backend
-      - run:
-          name: Backend smoke test.
-          command: |
-            # your code here
-            BACKEND_URL="http://$(cat /tmp/backend):3030/api/status"
-            echo "curl-ing ${BACKEND_URL}"
-            if curl ${BACKEND_URL}
-              then exit 0
-              else exit 1
-            fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-west-2.amazonaws.com"
-            echo "curl-ing ${URL}"
-            if curl ${URL} | grep -q "Welcome"
-              then exit 0
-              else exit 1
-            fi
-      # Here's where you will add some code to rollback on failure
-      - destroy-environment
-      - empty-bucket
-      - revert-migrations
-
-  cloudfront-update:
-    docker:
-      # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
-    steps:
-      # Checkout code from git
-      - checkout
-      # - run:
-      #     name: Install dependencies
-      #     command: |
-      #       # your code here
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            # your code here
-            # aws cloudformation deploy \
-            #   --template-file .circleci/files/cloudfront.yml \
-            #   --tags project=project4-cloudfront \
-            #   --stack-name udapeople-cloudfront \
-            #   --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID} &
-            aws cloudformation update-stack \
-            --use-previous-template \
-            --stack-name udapeople-cloudfront \
-            --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID},UsePreviousValue=false
-      # Here's where you will add some code to rollback on failure
-      - destroy-environment
-      - empty-bucket
-      - revert-migrations
+#  smoke-test:
+#    docker:
+#      # Lightweight Docker image
+#      - image: python:3.7-alpine3.11
+#    steps:
+#      # Checkout code from git
+#      - run:
+#          name: Install dependencies
+#          command: |
+#            # your code here
+#            apk add curl
+#            pip3 install --upgrade pip \
+#              && pip3 install awscli
+#      - run:
+#          name: Get backend url
+#          command: |
+#            # your code here
+#            BACKEND_IP=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/deployment)
+#            echo "I think the Backend IP is ${BACKEND_IP}"
+#            echo ${BACKEND_IP} > /tmp/backend
+#            echo -n "The file /tmp/backend contains IP:"
+#            cat /tmp/backend
+#      - run:
+#          name: Backend smoke test.
+#          command: |
+#            # your code here
+#            BACKEND_URL="http://$(cat /tmp/backend):3030/api/status"
+#            echo "curl-ing ${BACKEND_URL}"
+#            if curl ${BACKEND_URL}
+#              then exit 0
+#              else exit 1
+#            fi
+#      - run:
+#          name: Frontend smoke test.
+#          command: |
+#            # your code here
+#            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-west-2.amazonaws.com"
+#            echo "curl-ing ${URL}"
+#            if curl ${URL} | grep -q "Welcome"
+#              then exit 0
+#              else exit 1
+#            fi
+#      # Here's where you will add some code to rollback on failure
+#      - destroy-environment
+#      - empty-bucket
+#      - revert-migrations
+#
+#  cloudfront-update:
+#    docker:
+#      # Docker image here that supports AWS CLI
+#      - image: amazon/aws-cli
+#    steps:
+#      # Checkout code from git
+#      - checkout
+#      # - run:
+#      #     name: Install dependencies
+#      #     command: |
+#      #       # your code here
+#      - run:
+#          name: Update cloudfront distribution
+#          command: |
+#            # your code here
+#            # aws cloudformation deploy \
+#            #   --template-file .circleci/files/cloudfront.yml \
+#            #   --tags project=project4-cloudfront \
+#            #   --stack-name udapeople-cloudfront \
+#            #   --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID} &
+#            aws cloudformation update-stack \
+#            --use-previous-template \
+#            --stack-name udapeople-cloudfront \
+#            --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID},UsePreviousValue=false
+#      # Here's where you will add some code to rollback on failure
+#      - destroy-environment
+#      - empty-bucket
+#      - revert-migrations
 
   cleanup:
     docker:
@@ -525,8 +525,8 @@ workflows:
 #      - deploy-backend:
 #          requires: [run-migrations]
       - cleanup
-      - smoke-test:
-          requires: [deploy-backend]
+#      - smoke-test:
+#          requires: [deploy-backend]
 #      - smoke-test:
 #          requires: [deploy-backend, deploy-frontend]
 #      - cloudfront-update:
